#!/usr/bin/env python3
"""Compile `recipe:` blocks from manifest.yaml files into Dockerfiles.

A manifest may replace its hand-written Dockerfile with a declarative
`recipe:` block covering the "one app = one apt package list" case:

    recipe:
      apt: [libreoffice, libreoffice-gtk3]   # required, non-empty
      autostart: libreoffice     # XFCE autostart entry (Exec=<cmd>)
      # startup: <cmd>           # single-app on the bare base (WAAS_STARTUP)
      # program: <cmd>           # long-running app under supervisord
      # repo:                    # third-party apt repo, firefox pattern
      #   url: https://dl.google.com/linux/chrome/deb/
      #   suite: stable          # deb line suite (default: the repo default)
      #   component: main
      #   keyUrl: https://dl.google.com/linux/linux_signing_key.pub
      #   fingerprint: <40-hex>  # gpg fingerprint, verified at build time
      #   pin: google-chrome*    # apt preferences package glob

The output is `<context>/Dockerfile.generated` (gitignored, regenerated
by CI and `make recipes`), consumed by build_image.sh via `-f`. The
template bakes the non-negotiable hardening order used by every
hand-written node: FROM -> USER 0 -> install (no recommends, caches
purged) -> re-asserted suid strip -> files -> USER 1000:1000.

Ambiguity guard: a directory carrying BOTH a `recipe:` block and a
committed Dockerfile is refused — the source of truth must be unique.
A hand-written Dockerfile (no `recipe:`) always wins; anything beyond
the apt-simple case stays hand-written (see apps/firefox).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

GENERATED_NAME = "Dockerfile.generated"

RECIPE_KEYS = {"apt", "autostart", "startup", "program", "repo"}
REPO_KEYS = {"url", "suite", "component", "keyUrl", "fingerprint", "pin"}

HEADER = """\
# syntax=docker/dockerfile:1.7
# GENERATED by ci/recipe_compiler.py from {context}/manifest.yaml — DO NOT EDIT.
# Regenerate locally with: make recipes
ARG BASE_IMAGE
# hadolint ignore=DL3006
FROM ${{BASE_IMAGE}}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER 0
"""

# Packages install as the archive currently ships them (no per-package
# version pin): recipe: is scoped to apt-simple packages whose updates
# should ride every rebuild. A package needing a Renovate-tracked pin
# (see apps/firefox FIREFOX_VERSION) is exactly the "hand-written
# Dockerfile" case.
APT_SIMPLE = """\
# hadolint ignore=DL3008
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
{packages} \\
    && apt-get clean && \\
    rm -rf /var/lib/apt/lists/* /var/cache/* /var/log/*
"""

# Third-party repo, replicating apps/firefox/Dockerfile: keyring verified
# against its published fingerprint, origin priority-pinned so nothing
# can shadow the repo's packages. One deliberate departure from the
# firefox original: the bootstrap tools are released with `apt-mark auto
# + autoremove`, NOT `purge wget gpg` — a blind purge silently removes
# any recipe package that Depends: on wget (google-chrome-stable does),
# and the final dpkg -s turns any such removal into a build failure.
APT_WITH_REPO = """\
# hadolint ignore=DL3008
RUN apt-get update && \\
    apt-get install -y --no-install-recommends wget gpg && \\
    install -d -m 0755 /etc/apt/keyrings && \\
    # -4/--timeout/--tries: this fleet's IPv6 route is unreliable for
    # dual-stack vendor CDNs (blackholed to at least Azure Front Door),
    # so an unbounded/dual-stack wget can hang or return an empty key
    # (see apps/devtools/Dockerfile, apps/firefox/Dockerfile).
    wget -4 --timeout=20 --tries=3 -qO- {key_url} \\
        | gpg --dearmor -o /etc/apt/keyrings/{keyring}.gpg && \\
    gpg --show-keys --with-colons /etc/apt/keyrings/{keyring}.gpg \\
        | grep -q "^fpr:.*{fingerprint}" && \\
    echo "deb [signed-by=/etc/apt/keyrings/{keyring}.gpg] {repo_url} {suite} {component}" \\
        > /etc/apt/sources.list.d/{keyring}.list && \\
    printf 'Package: {pin}\\nPin: origin {origin}\\nPin-Priority: 1000\\n' \\
        > /etc/apt/preferences.d/{keyring} && \\
    apt-get update && \\
    apt-get install -y --no-install-recommends \\
{packages} \\
    && apt-mark auto wget gpg >/dev/null && \\
    apt-get autoremove -y --purge && \\
    dpkg -s{package_args} >/dev/null && \\
    apt-get clean && \\
    rm -rf /var/lib/apt/lists/* /var/cache/* /var/log/* /home/waas_user/.gnupg
"""

SUID_STRIP = """\
# Re-assert suid stripping (new packages may bring some back). Separate
# RUN: a trailing "|| true" on the apt chain would mask install failures.
RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} + 2>/dev/null || true
"""

AUTOSTART = """\
# Auto-start the app in the XFCE session (XDG autostart).
RUN printf '[Desktop Entry]\\nType=Application\\nName=%s\\nExec=%s\\nX-GNOME-Autostart-enabled=true\\n' \\
        '{name}' '{command}' > /etc/xdg/autostart/waas-app.desktop
"""

STARTUP = """\
# Session contract with the base entrypoint: WAAS_STARTUP replaces the
# openbox fallback (single-app image on the bare base).
ENV WAAS_STARTUP="{command}"
"""

# Long-running app under supervisord: ship an entrypoint.d hook (the
# same extension point base/ubuntu/rootfs/etc/waas/entrypoint.d/
# 50-sshd.sh uses) that renders the program fragment into the runtime
# supervisor.d at boot.
PROGRAM = """\
# supervisord-managed app: restart semantics via a runtime-rendered
# fragment (supervisord only includes $WAAS_RUNTIME_DIR/supervisor.d).
RUN install -d -m 0755 /etc/waas/entrypoint.d && \\
    printf '%s\\n' \\
        '# shellcheck shell=bash' \\
        '# 60-recipe-program.sh — generated by ci/recipe_compiler.py.' \\
        'cat > "${{RUNDIR}}/supervisor.d/60-{name}.conf" <<EOF' \\
        '[program:{name}]' \\
        'command={command}' \\
        'priority=60' \\
        'autorestart=true' \\
        'stdout_logfile=/dev/stdout' \\
        'stdout_logfile_maxbytes=0' \\
        'redirect_stderr=true' \\
        'EOF' \\
        > /etc/waas/entrypoint.d/60-recipe-program.sh
"""

FOOTER = "USER 1000:1000\n"


def _fail(context: str, msg: str) -> None:
    sys.exit(f"recipe ({context}): {msg}")


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "app"


def validate(recipe: dict, context: str, has_dockerfile: bool) -> None:
    if has_dockerfile:
        _fail(context, "both a recipe: block and a Dockerfile exist — "
                       "keep exactly one source of truth")
    unknown = set(recipe) - RECIPE_KEYS
    if unknown:
        _fail(context, f"unknown recipe key(s): {sorted(unknown)}")
    apt = recipe.get("apt")
    if not isinstance(apt, list) or not apt or not all(
        isinstance(p, str) and p and " " not in p for p in apt
    ):
        _fail(context, "recipe.apt must be a non-empty list of package names")
    if recipe.get("autostart") and recipe.get("startup"):
        _fail(context, "autostart (XFCE) and startup (bare base) are "
                       "mutually exclusive")
    repo = recipe.get("repo")
    if repo is not None:
        if not isinstance(repo, dict):
            _fail(context, "recipe.repo must be a map")
        unknown = set(repo) - REPO_KEYS
        if unknown:
            _fail(context, f"unknown recipe.repo key(s): {sorted(unknown)}")
        for key in ("url", "keyUrl", "fingerprint", "pin"):
            if not isinstance(repo.get(key), str) or not repo[key]:
                _fail(context, f"recipe.repo.{key} is required")
        if not re.fullmatch(r"[0-9A-Fa-f]{40}", repo["fingerprint"]):
            _fail(context, "recipe.repo.fingerprint must be the full "
                           "40-hex-digit GPG fingerprint")


def render(recipe: dict, context: str) -> str:
    parts = [HEADER.format(context=context)]

    packages = " \\\n".join(f"        {p}" for p in sorted(recipe["apt"]))
    repo = recipe.get("repo")
    if repo:
        origin = repo["url"].split("//", 1)[-1].split("/", 1)[0]
        parts.append(APT_WITH_REPO.format(
            key_url=repo["keyUrl"],
            keyring=_slug(origin),
            fingerprint=repo["fingerprint"].upper(),
            repo_url=repo["url"],
            suite=repo.get("suite", "stable"),
            component=repo.get("component", "main"),
            pin=repo["pin"],
            origin=origin,
            packages=packages,
            package_args="".join(f" {p}" for p in sorted(recipe["apt"])),
        ))
    else:
        parts.append(APT_SIMPLE.format(packages=packages))

    parts.append(SUID_STRIP)

    if recipe.get("autostart"):
        cmd = recipe["autostart"]
        parts.append(AUTOSTART.format(name=cmd.split()[0], command=cmd))
    if recipe.get("startup"):
        parts.append(STARTUP.format(command=recipe["startup"]))
    if recipe.get("program"):
        cmd = recipe["program"]
        parts.append(PROGRAM.format(name=_slug(cmd.split()[0].rsplit("/", 1)[-1]),
                                    command=cmd))

    parts.append(FOOTER)
    return "\n".join(parts)


def compile_recipe(manifest: dict, directory: Path, root: Path) -> str | None:
    """Materialise Dockerfile.generated when the manifest has a recipe.

    Returns the dockerfile name to build with (relative to the context)
    or None for hand-written-Dockerfile directories.
    """
    context = str(directory.relative_to(root))
    recipe = manifest.get("recipe")
    if recipe is None:
        if not (directory / "Dockerfile").is_file():
            _fail(context, "manifest has neither a recipe: block nor a "
                           "Dockerfile")
        return None
    validate(recipe, context, (directory / "Dockerfile").is_file())
    out = directory / GENERATED_NAME
    content = render(recipe, context)
    if not out.is_file() or out.read_text() != content:
        out.write_text(content)
        print(f"recipe: generated {context}/{GENERATED_NAME}")
    return GENERATED_NAME
